create table if not exists public.photos (
  id bigint generated by default as identity primary key,
  category text not null,
  category_name text not null,
  display_name text not null,
  instagram_url text,
  file_name text not null,
  storage_path text not null unique,
  created_at timestamptz not null default now()
);

alter table public.photos add column if not exists category_name text;
alter table public.photos add column if not exists display_name text;
alter table public.photos add column if not exists instagram_url text;
alter table public.photos add column if not exists likes_count integer not null default 0;

alter table public.photos enable row level security;

drop policy if exists "Anyone can view photo records" on public.photos;
create policy "Anyone can view photo records"
  on public.photos for select
  using (true);

drop policy if exists "Authenticated users can add photo records" on public.photos;
create policy "Authenticated users can add photo records"
  on public.photos for insert
  to authenticated
  with check (true);

drop policy if exists "Authenticated users can edit photo records" on public.photos;
create policy "Authenticated users can edit photo records"
  on public.photos for update
  to authenticated
  using (true)
  with check (true);

drop policy if exists "Authenticated users can delete photo records" on public.photos;
create policy "Authenticated users can delete photo records"
  on public.photos for delete
  to authenticated
  using (true);

insert into storage.buckets (id, name, public)
values ('gallery', 'gallery', true)
on conflict (id) do update set public = true;

drop policy if exists "Anyone can view gallery images" on storage.objects;
create policy "Anyone can view gallery images"
  on storage.objects for select
  using (bucket_id = 'gallery');

drop policy if exists "Authenticated users can upload gallery images" on storage.objects;
create policy "Authenticated users can upload gallery images"
  on storage.objects for insert
  to authenticated
  with check (bucket_id = 'gallery');

drop policy if exists "Authenticated users can delete gallery images" on storage.objects;
create policy "Authenticated users can delete gallery images"
  on storage.objects for delete
  to authenticated
  using (bucket_id = 'gallery');

create or replace function public.increment_photo_like(photo_id bigint)
returns void
language sql
security definer
set search_path = public
as $$
  update public.photos
  set likes_count = likes_count + 1
  where id = photo_id;
$$;

grant execute on function public.increment_photo_like(bigint) to anon, authenticated;